name: "Steve"
description: "Does some architectural analysis using LLMs and says if your docs are lacking"
author: "BF"
branding:
  icon: "rocket"
  color: "blue"
inputs:
  github_token:
    type: string
    required: true
  openai_api_token:
    type: string
    required: true
  docs_path:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up things
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Is it cached?
      id: cache-pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
    - name: Install
      shell: bash
      if: steps.cache-pip.outputs.cache-hit != 'true'
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Do stuff
      id: run_script
      shell: bash
      run: |
          OUTPUT=$(git diff origin/main -- | python "main.py")
          echo "script_output<<EOF" >> "$GITHUB_OUTPUT"
          echo "$OUTPUT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_token }}
        DOCS_PATH: ${{ inputs.docs_path }}

    - name: Make comment
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const commentBody = `${{ steps.run_script.outputs.script_output }}`;
          
          const prNumber = context.issue.number;
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: commentBody,
          });
