[package]
name = "steve"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.*", features = ["derive"] }
rig = "0.1.0"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
assert_cmd = "2.0"
