name: "Run Steve Action on PR"

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Steve Action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_token: ${{ secrets.OPENAI_API_TOKEN }}
          docs_path: "docs/"
